using System.Numerics;

namespace Kogl.Core.Resources;

/// <summary>3D Model structure composed of multiple sub-meshes and materials</summary>
public class Model : Resource
{
    public Mesh[] Meshes { get; set; } = [];
    public Material[] Materials { get; set; } = [];
    public int[] MeshMaterialIndices { get; set; } = [];
    public Matrix4x4 Transform { get; set; } = Matrix4x4.Identity;

    protected override void DisposeManaged()
    {
        foreach (Mesh mesh in Meshes)
        {
            mesh.Dispose();
        }

        // explicitly dispose materials automatically generated by this specific model context
        foreach (Material mat in Materials)
        {
            mat.Dispose();
        }
    }
}
